name: deepRLTrader
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.8.1=py37_0
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - gast=0.2.2=py37_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.9.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - importlib_metadata=1.5.0=py37_0
  - inflect=4.0.0=py37_1
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jaraco.itertools=5.0.0=py_0
  - jedi=0.16.0=py37_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_1
  - jupyter_core=4.6.1=py37_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libprotobuf=3.11.2=hd9629dc_0
  - libsodium=1.0.17=h01d97ff_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h0b31af3_0
  - mistune=0.8.4=py37h0b31af3_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=8.2.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1d=h0b31af3_0
  - opt_einsum=3.1.0=py_0
  - pandoc=2.9.1.1=0
  - parso=0.6.0=py_0
  - pexpect=4.8.0=py37_0
  - pip=20.0.2=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.2=py37h0a44026_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - pyrsistent=0.15.7=py37h0b31af3_0
  - python=3.7.6=h359304d_2
  - readline=7.0=h1de35cc_5
  - scipy=1.3.1=py37h1410ff5_0
  - send2trash=1.5.0=py_0
  - setuptools=45.1.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.8=py_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=2.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - altair==4.0.1
    - appnope==0.1.0
    - base58==2.0.0
    - blinker==1.4
    - boto3==1.11.9
    - botocore==1.14.9
    - chardet==3.0.4
    - click==7.0
    - coloredlogs==10.0
    - cycler==0.10.0
    - cython==0.29.14
    - docopt==0.6.2
    - docutils==0.15.2
    - enum-compat==0.0.3
    - future==0.18.2
    - humanfriendly==4.18
    - idna==2.8
    - importlib-metadata==1.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.1
    - json5==0.8.5
    - jupyter-contrib-core==0.3.3
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-server==1.0.6
    - keras==2.3.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.2
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - pathtools==0.1.2
    - patsy==0.5.1
    - pickleshare==0.7.5
    - pillow==7.0.0
    - plotly==4.5.0
    - pmdarima==1.5.2
    - pydeck==0.2.1
    - pyobjc-core==6.1
    - pyobjc-framework-cocoa==6.1
    - pyobjc-framework-fsevents==6.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.0
    - pytz==2019.3
    - pyyaml==5.3
    - pyzmq==18.1.1
    - requests==2.22.0
    - retrying==1.3.3
    - s3transfer==0.3.2
    - scikit-learn==0.22.1
    - seaborn==0.10.0
    - sklearn==0.0
    - statsmodels==0.11.0
    - streamlit==0.53.0
    - ta==0.5.11
    - tensorboardx==2.0+a7f3124
    - terminado==0.8.3
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==5.1.1
    - tqdm==4.42.0
    - tzlocal==2.0.0
    - urllib3==1.25.8
    - validators==0.14.2
    - watchdog==0.10.0
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: /opt/anaconda3/envs/deepRLTrader

